name: record_linux
description: Linux specific implementation for record package called by record_platform_interface.
version: 0.7.1
publish_to: none
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    git: https://github.com/kumsumit/record_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
